local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 5.0
   publish_frequency: 2.0
   #inflation_radius: 0.05
   robot_radius: 0.05
   width: 1
   height: 1
   resolution: 0.02
   transform_tolerance: 0.5
   rolling_window: true

   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

