TebLocalPlannerROS:

# Robot Configuration Parameters - Kobuki
  controller_frequency: 10.0

  max_vel_x: 0.3  # 0.55
  min_vel_x: 0.0 

  max_vel_y: 0.0  # diff drive robot
  min_vel_y: 0.0  # diff drive robot

  #max_vel_trans: 0.1 # choose slightly less than the base's capability
  #min_vel_trans: 0.02  # this is the min trans velocity when there is negligible rotational velocity
  #trans_stopped_vel: 0.02

  # Warning!
  #   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  #   are non-negligible and small in place rotational velocities will be created.

  max_vel_theta: 0.3  # choose slightly less than the base's capability
  min_vel_theta: 0.1  # this is the min angular velocity when there is negligible translational velocity
  #theta_stopped_vel: 0.1
  
  acc_lim_x: 0.2 
  acc_lim_theta: 0.2
  acc_lim_y: 0.0      # diff drive robot

  min_turning_radius: 0.0
  
  # Footprint parameters
  footprint_model: # types: "point", "circular", "line", "two_circles", "polygon"
    type: "point"
    # these are not relevant parameters
    # radius: 0.2 # for type "circular"
    # line_start: [-0.3, 0.0] # for type "line"
    # line_end: [0.3, 0.0] # for type "line"
    # front_offset: 0.2 # for type "two_circles"
    # front_radius: 0.2 # for type "two_circles"
    # rear_offset: 0.2 # for type "two_circles"
    # rear_radius: 0.2 # for type "two_circles"
    # vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3  # 0.05
  xy_goal_tolerance: 0.05  # 0.10
  free_goal_vel: False
  complete_global_plan: True

# Trajectory Configuration Parameters
  dt_ref: 0.2
  dt_hysteresis : 0.02
  min_samples: 3
  global_plan_overwrite_orientation : true
  global_plan_viapoint_sep : -0.1
  max_global_plan_lookahead_dist: 1.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses : 4
  publish_feedback : false
  shrink_horizon_backup: true
  allow_init_with_backwards_motion: false
  exact_arc_length: false
  shrink_horizon_min_duration: 10.0

# Obstacle Parameters
  min_obstacle_dist: 0.06
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 0.2
  obstacle_poses_affected: 10
  inflation_dist: 0.2
  include_dynamic_obstacles: false
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5.0

# Optimization Parameters
  no_inner_iterations: 5
  no_outer_iterations: 4
  penalty_epsilon: 0.05
  weight_max_vel_x: 2.0
  weight_max_vel_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 1.0
  # weight_kinematics_turning_radius: 1.0
  weight_optimaltime: 1.0
  weight_obstacle: 50.0
  weight_viapoint: 1.0
  weight_inflation: 0.1
  weight_adapt_factor: 2.0

# Parallel Planning in distinctive Topologies
  enable_homotopy_class_planning : true
  enable_multithreading: true
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_viapoint_cost_scale: 1.0
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 6
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 1.0
  visualize_hc_graph: false
  viapoints_all_candidates: true
  switching_blocking_period: 0.0

# Miscellaneous Parameters
  odom_topic: "odom"
  map_frame: "map"

# ez lehet nem kell bele
# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom